spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/omnihealth_platform?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/platform/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE